name: locust-swarm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - scipy
  - jupyter
  - ffmpeg            
  - pip
  - pip:
      - ipywidgets    
